# netlify.toml
# Netlify configuration file for YapaNow

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Use Node.js 20 for better crypto module support
  NODE_VERSION = "20"
  
  # Install dev dependencies (required for TypeScript)
  NPM_FLAGS = "--production=false"
  
  # Set build environment variables
  NODE_ENV = "production"
  
  # Increase Node.js memory limit for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Ensure crypto module is available
  GENERATE_SOURCEMAP = "false"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function configuration
[functions]
  node_bundler = "esbuild"
  
  # Include files in functions
  included_files = ["netlify/functions/**"]